apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - gitrepository.yaml
  - namespace.yaml
  - helmrelease-csi-driver.yaml
  - helmrelease-gcp-plugin.yaml
