---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Flux System (Operator and Instance)
  - flux-system

  # Core Infrastructure
  - gateway-api-crds.yaml
  - secrets-store-csi-driver.yaml
  - cert-manager.yaml
  - monitoring.yaml

  # Security & Policy
  - priorityclasses.yaml